### ISSUE TITLE
Add better Example-File

### ISSUE THREAD

**Issue by xstable** [joshrlesch/fastlane-plugin-yarn#11]
Need to add a more detailed  Example-files to show how to call it the right way with Parameters.
Doing only `yarn` in the example file don't make any sense at all!  ;)

**Comment by joshrlesch** [comment]
@xstable are you talking about this file? https://github.com/joshrlesch/fastlane-plugin-yarn/blob/master/fastlane/Fastfile#L2

**Comment by xstable** [comment]
Yes, because you notice to have a look into this file to see Examples, but there are not really examples in the file. 
So I'll send a PR. You can use it, if you like

**Comment by joshrlesch** [comment]
k. I already have a PR open and will just update it in there. Thanks for the help though!

**Comment by joshrlesch** [comment]
Fixed in latest release. https://github.com/joshrlesch/fastlane-plugin-yarn/releases/tag/v1.2
