### ISSUE TITLE
Not able to write files to disk

### ISSUE THREAD

**Issue by T-L-P** [joshrlesch/fastlane-plugin-yarn#14]
Hey, Im trying to use `fastlane-plugin-yarn` to execute a node script which is rewriting a `.env` file.
Executing it straight with yarn works fine, but when using the plugin it's not writing the to the file.
Any idea what might be the issue?

thanx for any help

**Comment by joshrlesch** [comment]
@T-L-P Are there any errors? Can you share your `yarn` action in your Fastfile? The plugin just uses a Ruby system command to execute `yarn` so Im wondering if its a permission issue with your Ruby setup?

**Comment by T-L-P** [comment]
Wow thanx for that quick reply!

No, sadly no errors :(

but I have to admit that I'm pretty new to ruby, so your suspicion about permission issues might be true, but I would have no clou how to change it! :)

that's the yarn script I'm trying to execute
```
"env:dev": "node ./scripts/dotenv.js dev"
```
and her is the yarn action:
```
yarn(command: "env:#{env}") 
```

and here is the output:
```
[13:48:13]: ------------------
[13:48:13]: --- Step: yarn ---
[13:48:13]: ------------------
[13:48:13]: $ yarn env:stg
[13:48:13]: ▸ yarn run v1.22.4
[13:48:13]: ▸ $ node ./scripts/dotenv.js stg
[13:48:13]: ▸ Done in 0.13s.

+------+--------+-------------+
|      fastlane summary       |
+------+--------+-------------+
| Step | Action | Time (in s) |
+------+--------+-------------+
| 1    | yarn   | 0           |
+------+--------+-------------+
```

**Comment by T-L-P** [comment]
just did a test:
```
lane :test do
    # yarn(command: "env:" + "stg")
    File.open("log.txt", "w") { |f| f.write "#{Time.now} - User logged in\n" }
  end
```
It did create the file and wrote to it. So that would speak against the permission issue, right?

**Comment by joshrlesch** [comment]
@T-L-P  Sorry just trying to understand. But you mention the script you're trying to execute is
`"env:dev": "node ./scripts/dotenv.js dev"`

but in the output, it says it tried to run `yarn env:stg`

Is the mismatch between `dev` and `stg` an issue?

**Comment by joshrlesch** [comment]
I just tried something similar to you and it seem to be working.
`"env:dev": "node ./Scripts/test.js"`
```
  lane :test do
    yarn(command: "env:dev")
  end
```
output
```
[09:49:55]: ------------------
[09:49:55]: --- Step: yarn ---
[09:49:55]: ------------------
[09:49:55]: $ yarn env:dev
[09:49:55]: ▸ yarn run v1.22.4
[09:49:55]: ▸ warning package.json: No license field
[09:49:55]: ▸ $ node ./Scripts/test.js
[09:49:55]: ▸ hello world
[09:49:55]: ▸ Done in 0.25s.
```

**Comment by T-L-P** [comment]
sorry, `DEV` and `STG` was just a copy paste bug when writing the comment.
both scripts exist.

In your test did the `./Scripts/test.js` wrote smth. to a file?
Because my script does also execute but not writing the file.

```
[15:55:19]: ------------------
[15:55:19]: --- Step: yarn ---
[15:55:19]: ------------------
[15:55:19]: $ yarn env:stg
[15:55:19]: ▸ yarn run v1.22.4
[15:55:19]: ▸ $ node ./scripts/dotenv.js stg
[15:55:20]: ▸ TEST EXECUTION
[15:55:20]: ▸ Done in 0.48s.
```

**Comment by T-L-P** [comment]
ok, its not related to the yarn plugin because:
```
sh("yarn", "env:stg")
```
does not write to the file either. :(
sorry for waisting your time here and thanx alot for your effort.
hm.. but no idea how to continue

**Comment by joshrlesch** [comment]
Maybe put some logging into your script so you can see what it's trying to do or where its failing. But since this isn't an issue with the yarn plugin, Im going to close the issue.

Good luck
