### ISSUE TITLE
yarn version

### ISSUE THREAD

**Issue by Pranit-Harekar** [joshrlesch/fastlane-plugin-yarn#6]
What yarn version does it use? Does it use the version that is installed globally on the system? Actually I want to version control yarn.

**Comment by Pranit-Harekar** [comment]
@joshrlesch  Just tagging you directly since there aren't any issues here, so you might not be active here. 😄

**Comment by joshrlesch** [comment]
yup, it just uses the global version installed.

**Comment by Pranit-Harekar** [comment]
Got it! Thanks.
